import { GameStatus } from "@/type/game";
const neutralImages = [
  "couple-neutral-1",
  "couple-neutral-2",
  "couple-neutral-3",
  "couple-neutral-4",
  "man-neutral-1",
  "man-neutral-2",
  "man-neutral-3",
  "man-neutral-4",
  "man-neutral-5",
  "woman-neutral-1",
  "woman-neutral-2",
  "woman-neutral-3",
  "woman-neutral-4",
  "woman-neutral-5",
  "woman-neutral-6",
  "woman-neutral-7",
  "woman-neutral-8",
  "woman-neutral-9",
  "woman-neutral-10",
];

export const gameStatusImages: Record<GameStatus, string[]> = {
  WON: [
    "couple-smile-1",
    "couple-smile-2",
    "couple-smile-3",
    "couple-smile-4",
    "couple-smile-5",
    "couple-smile-6",
    "couple-smile-7",
    "man-smile-1",
    "man-smile-2",
    "woman-smile-1",
    "woman-smile-2",
    "woman-smile-3",
    "woman-smile-4",
    "woman-smile-5",
    "woman-smile-6",
    "woman-smile-7",
    "woman-smile-8",
    "woman-smile-9",
    "woman-smile-10",
    "woman-smile-11",
    "woman-smile-12",
    "woman-smile-13",
  ],

  LOST: [
    "man-sad-1",
    "man-sad-2",
    "man-sad-3",
    "man-sad-4",
    "woman-sad-1",
    "woman-sad-2",
    "woman-sad-3",
    "woman-sad-4",
    "woman-sad-5",
  ],
  ENDED: neutralImages,
  IN_PROGRESS: neutralImages,
  INFO_PAUSE: neutralImages,
  NOT_STARTED: neutralImages,
} as const;

const path = "@/assets/images/sd/";

export const imagePaths: Record<string, string> = {
  "couple-neutral-1": require(`${path}couple-neutral-1.webp`),
  "couple-neutral-2": require(`${path}couple-neutral-2.webp`),
  "couple-neutral-3": require(`${path}couple-neutral-3.webp`),
  "couple-neutral-4": require(`${path}couple-neutral-4.webp`),
  "man-neutral-1": require(`${path}man-neutral-1.webp`),
  "man-neutral-2": require(`${path}man-neutral-2.webp`),
  "man-neutral-3": require(`${path}man-neutral-3.webp`),
  "man-neutral-4": require(`${path}man-neutral-4.webp`),
  "man-neutral-5": require(`${path}man-neutral-5.webp`),
  "woman-neutral-1": require(`${path}woman-neutral-1.webp`),
  "woman-neutral-2": require(`${path}woman-neutral-2.webp`),
  "woman-neutral-3": require(`${path}woman-neutral-3.webp`),
  "woman-neutral-4": require(`${path}woman-neutral-4.webp`),
  "woman-neutral-5": require(`${path}woman-neutral-5.webp`),
  "woman-neutral-6": require(`${path}woman-neutral-6.webp`),
  "woman-neutral-7": require(`${path}woman-neutral-7.webp`),
  "woman-neutral-8": require(`${path}woman-neutral-8.webp`),
  "woman-neutral-9": require(`${path}woman-neutral-9.webp`),
  "woman-neutral-10": require(`${path}woman-neutral-10.webp`),
  "couple-smile-1": require(`${path}couple-smile-1.webp`),
  "couple-smile-2": require(`${path}couple-smile-2.webp`),
  "couple-smile-3": require(`${path}couple-smile-3.webp`),
  "couple-smile-4": require(`${path}couple-smile-4.webp`),
  "couple-smile-5": require(`${path}couple-smile-5.webp`),
  "couple-smile-6": require(`${path}couple-smile-6.webp`),
  "couple-smile-7": require(`${path}couple-smile-7.webp`),
  "man-smile-1": require(`${path}man-smile-1.webp`),
  "man-smile-2": require(`${path}man-smile-2.webp`),
  "woman-smile-1": require(`${path}woman-smile-1.webp`),
  "woman-smile-2": require(`${path}woman-smile-2.webp`),
  "woman-smile-3": require(`${path}woman-smile-3.webp`),
  "woman-smile-4": require(`${path}woman-smile-4.webp`),
  "woman-smile-5": require(`${path}woman-smile-5.webp`),
  "woman-smile-6": require(`${path}woman-smile-6.webp`),
  "woman-smile-7": require(`${path}woman-smile-7.webp`),
  "woman-smile-8": require(`${path}woman-smile-8.webp`),
  "woman-smile-9": require(`${path}woman-smile-9.webp`),
  "woman-smile-10": require(`${path}woman-smile-10.webp`),
  "woman-smile-11": require(`${path}woman-smile-11.webp`),
  "woman-smile-12": require(`${path}woman-smile-12.webp`),
  "woman-smile-13": require(`${path}woman-smile-13.webp`),
  "man-sad-1": require(`${path}man-sad-1.webp`),
  "man-sad-2": require(`${path}man-sad-2.webp`),
  "man-sad-3": require(`${path}man-sad-3.webp`),
  "man-sad-4": require(`${path}man-sad-4.webp`),
  "woman-sad-1": require(`${path}woman-sad-1.webp`),
  "woman-sad-2": require(`${path}woman-sad-2.webp`),
  "woman-sad-3": require(`${path}woman-sad-3.webp`),
  "woman-sad-4": require(`${path}woman-sad-4.webp`),
  "woman-sad-5": require(`${path}woman-sad-5.webp`),
};
